/* ============================================================
   recipes.js - 업사이클 제작 레시피 목록
   새 레시피를 추가할 때 이 배열에만 추가하면 됩니다.
   ============================================================ */

const RECIPES = [
  {
    id:          'solar_lamp',
    name:        '태양광 가로등',
    emoji:       '💡',
    ingredients: { plastic: 5, glass: 3, metal: 2 },
    description: '버려진 병과 캔으로 만든 친환경 태양광 조명',
    effect:      '섬 밤 밝기 증가',
    stackLimit:  3,
    unlockLevel: 1,
    islandEffect:{ colorRestore: 15, happiness: 5 },
    co2Saved:    2.5,
  },
  {
    id:          'eco_bench',
    name:        '업사이클 벤치',
    emoji:       '🪑',
    ingredients: { plastic: 8, metal: 3 },
    description: '플라스틱 병을 녹여 만든 공원 벤치',
    effect:      '섬 행복도 증가',
    stackLimit:  3,
    unlockLevel: 1,
    islandEffect:{ colorRestore: 10, happiness: 8 },
    co2Saved:    1.8,
  },
  {
    id:          'paper_garden',
    name:        '종이 꽃밭',
    emoji:       '🌸',
    ingredients: { paper: 10, plastic: 2 },
    description: '신문지·폐지로 만든 알록달록한 꽃 조형물',
    effect:      '생태 다양성 증가',
    stackLimit:  3,
    unlockLevel: 1,
    islandEffect:{ colorRestore: 10, happiness: 6 },
    co2Saved:    1.2,
  },
  {
    id:          'windmill',
    name:        '재활용 풍차',
    emoji:       '🌀',
    ingredients: { metal: 10, paper: 5, plastic: 3 },
    description: '캔과 신문지로 만든 미니 바람개비 발전기',
    effect:      '재생 에너지 생산',
    stackLimit:  3,
    unlockLevel: 2,
    islandEffect:{ colorRestore: 20, happiness: 10 },
    co2Saved:    4.0,
  },
  {
    id:          'greenhouse',
    name:        '유리 온실',
    emoji:       '🌿',
    ingredients: { glass: 15, metal: 8, paper: 3 },
    description: '유리병을 이어 만든 식물 성장 온실',
    effect:      '식물 성장 가속',
    stackLimit:  3,
    unlockLevel: 2,
    islandEffect:{ colorRestore: 25, happiness: 15 },
    co2Saved:    5.0,
  },
  {
    id:          'water_purifier',
    name:        '정수 시설',
    emoji:       '💧',
    ingredients: { plastic: 10, glass: 8, metal: 5, paper: 2 },
    description: '다양한 재활용 재료로 만든 자연 정수기',
    effect:      '물 오염도 감소',
    stackLimit:  3,
    unlockLevel: 3,
    islandEffect:{ colorRestore: 30, happiness: 20 },
    co2Saved:    6.5,
  },
  {
    id:          'eco_house',
    name:        '에코 하우스',
    emoji:       '🏠',
    ingredients: { plastic: 20, glass: 10, metal: 10, paper: 10 },
    description: '100% 재활용 재료로 지은 친환경 주택',
    effect:      '섬 주민 유입',
    stackLimit:  3,
    unlockLevel: 4,
    islandEffect:{ colorRestore: 40, happiness: 30 },
    co2Saved:    10.0,
  },
];
